src/i18n/fr.json

Hello,
I make some translations for french users
Thanks

Add french translation

---

readme-zh.md

Add Traditional Chinese README.md

---

src/component/action.jsx
src/component/avatar.jsx
src/component/button.jsx
src/component/comment.jsx
src/component/svg.jsx

Hi,
有点想把代码再拆细一点，多用 functional component 和 解构，尤其是 gitalk.jsx 里面的代码，不知道大佬们是什么意见，动手之前先来问一下

improve readability

---

readme-cn.md
readme-zh.md
readme.md

Add badges showing the latest gitalk version with the link on cdnjs.

Add CDNJS version badges in readme files

---

package.json
readme-cn.md
readme-zh.md
readme.md
src/i18n/en.json
src/i18n/es-ES.json
src/i18n/fr.json
src/i18n/ru.json
src/i18n/zh-CN.json
src/i18n/zh-TW.json

Changes the casing of `Github` to `GitHub`. 🌮 🎉 :octocat:

Github => GitHub

---

src/style/index.styl

fix: mobile button style (#154)

---

readme-cn.md
readme-zh.md
readme.md

增加关于html中div的描述（issue #170 readme 改进提议）

---

readme.md

change「Add a container to you page」to「Add a container to your page」

fix: change you to your in readme.md

---

readme-cn.md
readme-zh.md
readme.md

See Vssue:
- [Homepage](https://vssue.js.org)
- [Repo](https://github.com/meteorlxy/vssue)

chore: add vssue to similar projects

---

src/i18n/en.json

Guy sounds a bit harsh and less inclusive than person. I've updated the wording slightly to be a little more open.
Thanks for this awesome app!
/cc @booxood

A little more friendly message

---

src/gitalk.jsx

Reduce unnecessary 302 redirects

chore: http -> https

---

src/gitalk.jsx

auto refresh comment after issue created.

feat: refresh after issue created.

---

src/gitalk.jsx

if this.token is null, there is no need to fetch user profile through github api

if this.token is null, there is no need to fetch user profile through github api

---

readme-cn.md
readme.md

Improve `readme.md`, refine the order, make it easier for users to use it
1. change `readme.md` and `readme-cn.md`
Maybe my description is not accurate, you can continue to modify it to make it easier to use

Perfect usage document

---

readme-cn.md
readme-zh.md
readme.md
src/component/comment.jsx
src/i18n/index.js
src/i18n/pl.json

feat: add Polish translations

---

readme-cn.md
readme-zh.md
readme.md
src/i18n/index.js
src/i18n/ko.json

Checked all above. 
Added Korean translation.

feat: add Korean language support

---

package.json
src/component/comment.jsx
src/component/comment.spec.js

Checked all above. 
Upgraded date-fns (from 1.28.5 to 2.16.1) and refactored code to match the version. 
Added some test for date-fns (Korean, Deutsch)

refactor: upgrade date-fns (1.28.5 -> 2.16.1)

---

src/component/comment.jsx
src/gitalk.jsx

fix: #369 Update comment not work when post like or unlike

---

readme-cn.md
readme-zh.md
readme.md
src/i18n/fa.json
src/i18n/index.js

Add persian fa language

---

readme-cn.md
readme-zh.md
readme.md
src/i18n/index.js
src/i18n/ja.json

chore(i18n): add Japanese lang support

---

src/i18n/fr.json

Hi!
This PR improves the translations of some french sentences.

fix(i18n): improve french translation
